@baseUrl = http://localhost:3000/api

POST {{baseUrl}}/milestones
Content-Type: application/json

{
    "Name": "est",
    "Budget": 9.5,
    "StartDate":"1/1/2022",
    "EndDate":"1/5/2000"
}

###
GET {{baseUrl}}/milestones

###
DELETE {{baseUrl}}//milestones/30e3a590-bd88-46ed-ae44-ac21eb1e6b4b

###
GET  {{baseUrl}}/milestones?filter[Name]=est
